# Generated by Django 3.1 on 2020-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=30)),
                ('mobile_no', models.PositiveIntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sub_title', models.CharField(default='', max_length=70)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
